import React, { createContext, useState } from "react";

export const BlogValue = createContext();
const pl = [
  {
    category: "tech",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "What is Lorem Ipsum",
    writer: "wefwgrwg wggwef",
    id: "1",
  },
  {
    category: "tech",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 2",
    writer: "wefwgrwg wggwef",
    id: "2",
  },
  {
    category: "tech",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 3",
    writer: "wefwgrwg wggwef",
    id: "3",
  },
  {
    category: "hospi",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 4",
    writer: "wefwgrwg wggwef",
    id: "4",
  },
  {
    category: "hospi",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 5",
    writer: "wefwgrwg wggwef",
    id: "5",
  },
  {
    category: "hospi",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 6",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 7",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 8",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 9",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 10",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 11",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 12",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 13",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 14",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 15",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 16",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 17",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 18",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 19",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 20",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 21",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 22",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 23",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 24",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 25",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 26",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 27",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 28",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 29",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo 30",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
  {
    category: "college",
    description: "efwewgewg wge wge er  e b b bd bd bd  d",
    title: "hello koko melon jadoo",
    writer: "wefwgrwg wggwef",
    id: "243546",
  },
];

const BlogContext = ({ children }) => {
  const [blogArr, setBlogArr] = useState(pl);
  const [bolg, setBlog] = useState({});
  const [editedbolgID, setEditedbolgID] = useState(null);
  const [bolgEdited, setBolgEdited] = useState(false);
  return (
    <BlogValue.Provider
      value={{
        blogArr,
        setBlogArr,
        bolg,
        setBlog,
        bolgEdited,
        setBolgEdited,
        editedbolgID,
        setEditedbolgID,
      }}
    >
      {children}
    </BlogValue.Provider>
  );
};

export default BlogContext;
